/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alex' at '12.07.15 8:06' with Gradle 2.4
 *
 * @author Alex, @date 12.07.15 8:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
